apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx

spec:
  replicas: 5

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:              # ✅ labels (plural)
        app: nginx
    spec:                  # ✅ pod spec inside template
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

