kind: Jobs
apiVersion: v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelims: 1
  template:
    metadate:
      labels:
        name: demo-job-pod
        app: batch-task
      conatiner: batch

    spec:
      container:
        - name: batch-container
          image: busybox:latest
          command: ['sh', '-c', 'echo "Hello World" && sleep 30']
          restartPolicy: Never
