apiVersion: apps/v1
kind: Deployment

metadata:
  name: music-app-deployment
  namespace: nginx

spec:
  replicas: 2 #how many repicas should be have

  selector:
    matchLabels:
      app: music-app

  template:
    metadata:
      labels:
        app: music-app

    spec:
      containers:
        - name: music-app
          image: ayushraturi/music-app:latest   
          
          ports:
            - containerPort: 80

          # Mount the PVC inside container
          volumeMounts:
            - name: music-pvc-data   # Must match volume name
              mountPath: /var/www/html

      # Volumes must be inside pod spec
      volumes:
        - name: music-pvc-data
          persistentVolumeClaim:
            claimName: music-pvc

